backend:
  name: git-gateway
  repo: openpracticelibrary/openpracticelibrary
  branch: staging

publish_mode: editorial_workflow
media_folder: "static/images" # Media files will be stored in the repo under images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "practice" # Used in routes, e.g., /admin/collections/blog
    label: "Practice" # Used in the UI
    folder: "content/practice" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title of practice", hint: "The name of the practice", name: "title", widget: "string"}
      - {label: "Subtitle", hint: "Catchy one liner for the article", name: "subtitle", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Authors", hint: "Comma-separated list of github usernames eg., springdo, rdebeasi, tdbeattie", name: "authors", widget: "list", default: []}
      - {label: "Area of the Library Loop", hint: "Choose the position on the Library Loop where your practice lives", name: "area", widget: "select", options:
          [{label: "Discovery - Why", value: "discovery-loop-why"},
          {label: "Discovery - Outcomes", value: "discovery-loop-outcomes"},
          {label: "Options", value: "options"},
          {label: "Delivery - Deliver", value: "delivery-deliver"},
          {label: "Delivery - Measure & Learn", value: "delivery-measure-and-learn"},
          {label: "Foundation - Culture & Collaboration", value: "foundation-culture-and-collaboration"},
          {label: "Foundation - Technical",  value: "foundation-technical"}]}
      - {label: "Related Perspectives", hint: "Comma-separated list of slugs e.g., domain-driven-design, product-ownership", name: "perspectives", widget: "list", default: [], required: false}
      - {label: "Tile icon", name: "icon", hint: "Icon to be used on the home screen and cards for the practice", widget: "image", required: false}
      - {label: "Jumbotron image", hint: "Large full width image for under the titles", name: "jumbotron", widget: "image", required: false}
      - {label: "Jumbotron alt text", hint: "Accessible description of the image for screen readers", name: "jumbotronAlt", widget: "string", required: false}
      - {label: "No. of people required", hint: "How many people are needed for the practice eg 2+ or 10", name: "people", widget: "string", required: false}
      - {label: "Time length", hint: "How long is needed to facilitate this practice", name: "time", widget: "string", required: false}
      - {label: "Facilitation difficulty", hint: "How difficult is it to facilitate this practice", name: "difficulty", widget: "select", required: false, options:
          [{label: "Easy", value: "easy"},
          {label: "Moderate", value: "moderate"},
          {label: "Hard", value: "hard"}]}
      - {label: "Expected participants", hint: "Who should attend when running this practice? eg., The Team, The Product Owner, BAs", name: "participants", required: false, widget: "list", default: []}
      - {label: "Body", name: "body", widget: "markdown", default: "## What is it? \n\n## Why use it? \n\n## Further Information\n\n"}
  - name: "perspective" # Used in routes, e.g., /admin/collections/blog
    label: "Perspective" # Used in the UI
    folder: "content/perspective" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", hint: "The name of the perspective", name: "title", widget: "string"}
      - {label: "Subtitle", hint: "Catchy one liner for the perspective", name: "subtitle", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Authors", hint: "Comma-separated list of github usernames eg., springdo, rdebeasi, tdbeattie", name: "authors", widget: "list", default: []}
      - {label: "Jumbotron image", hint: "Large full width image for under the titles", name: "jumbotron", widget: "image", required: false}
      - {label: "Jumbotron alt text", hint: "Accessible description of the image for screen readers", name: "jumbotronAlt", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown", default: "## What is it? \n\n## Why use it? \n\n## Further Information\n\n"}
  - name: "page" # Used in routes, e.g., /admin/collections/blog
    label: "Page" # Used in the UI
    folder: "content/page" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Authors", name: "authors", widget: "list", default: []}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Menu", name: "menu", widget: "select", required: false, options:
          [{label: "True", value: "main"},
          {label: "False", value: ""}]}
      - {label: "Menu weight", name: "weight", widget: "string", required: false, pattern: ["^[0-9]", "Must be a number between one and 9"]}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "author" # Used in routes, e.g., /admin/collections/blog
    label: "Author" # Used in the UI
    format: "toml"
    extension: "toml"
    folder: "data/content/author" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{github}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Name", hint: "Your full name to be displayed on an article", name: "title", widget: "string"}
      - {label: "GitHub Username", hint: "Your github username", name: "github", widget: "string"}
      - {label: "About you", hint: "Short description of you", name: "bio", widget: "text", required: false, pattern: [".{0,120}", "Must have at least 120 characters"]}
      - {label: "Location", hint: "Where are you based", name: "location", widget: "string", required: false}
      - {label: "WebSite", hint: "Your personal blog or website", name: "website", widget: "string", required: false}
